# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

vars:
  GREETING: Hello, world!

tasks:
  default:
    desc: list tasks
    cmds:
      - task -l
    silent: true

  bench:prepare:
    desc: prepare benchmark
    cmds:
      - docker compose --profile bench build
      - docker compose --profile bench up -d benchn bencht bencha workload
      - docker compose exec bencha sh -c "cd /website ; sh /makedata.sh"

  bench:run:
    desc: run benchmark
    cmds:
      - caffeinate docker compose exec workload sh -x /mark.sh
      # - systemd-inhibit docker compose exec workload sh -x /mark.sh

  bench:cleanup:
    desc: cleanup benchmark
    cmds:
      - docker compose --profile bench down -v

  bench:go:
    desc: go test benchmark
    cmds:
      - go test -bench 'Benchmark' -benchmem -benchtime=200ms

  bench:yaegi:
    desc: go test benchmark
    cmds:
      - yaegi test -bench 'Benchmark' -benchmem -benchtime=200ms

  build:
    desc: build
    cmds:
      - go build

  build:pkg:
    desc: build
    cmds:
      - goreleaser --snapshot --clean

  fmt:
    desc: fmt
    cmds:
      - go fmt ./...
      - go vet ./...

  lint:
    desc: lint
    cmds:
      - golangci-lint run

  test:
    desc: test
    cmds:
      - go test -v ./... -coverprofile=./cover.out -covermode=atomic
        -coverpkg=./...
      - go tool cover -func=cover.out

  test:yaegi:
    desc: test yaegi
    cmds:
      - yaegi test -v

  scan:
    desc: scan code
    cmds:
      - ~/go/bin/govulncheck ./...
      - ~/go/bin/gosec ./...

  update:
    desc: update deps
    cmds:
      - go get -u
      - go mod tidy
