name: branch

on:
  push:
    branches-ignore: [main]
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
    - uses: wtnb75/actions/golang@v1
    - name: prepare yaegi
      run: go install github.com/traefik/yaegi/cmd/yaegi@v0.16.1
      shell: bash
    - uses: wtnb75/actions/gotest@v1
    - name: yaegi test
      run: yaegi test .
      shell: bash
